spring:
  data:
    mongodb:
      uri: mongodb+srv://jacilopezwork:Smokione123@canaryrankings.2pa9pdt.mongodb.net/warhammerDB?retryWrites=true&w=majority&appName=canaryrankings
      database: warhammerDB