spring:
  data:
    mongodb:
      uri: mongodb+srv://jacilopezwork:Smokione123@canaryrankings.2pa9pdt.mongodb.net/warhammerDB?retryWrites=true&w=majority&appName=canaryrankings
      database: warhammerDB
bcp:
  username: "kanarias.open@gmail.com"
  password: "Tito&2026"
auth:
  secret: "maja-13-10-22-123654789--aeldari-emperor-tau-drukhari-necron"
  username: "ADMIN"
  password: "1234"
