spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: ${SPRING_DATA_MONGODB_DATABASE}
server:
  port: ${PORT:8080}

bcp:
  username: ${BCP_USERNAME}
  password: ${BCP_PASSWORD}

auth:
  secret: ${AUTH_SECRET}
  username: ${AUTH_USERNAME}
  password: ${AUTH_PASSWORD}